CREATE TABLE `T_AREA` (
  `ID` bigint(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CODE` varchar(15) COLLATE utf8_bin DEFAULT '' COMMENT '编码',
  `VALUE` varchar(20) COLLATE utf8_bin DEFAULT '' COMMENT '名称',
  `PARENT` varchar(15) COLLATE utf8_bin DEFAULT '' COMMENT '父code',
  `LEVEL` int(2) DEFAULT NULL COMMENT '级别',
  `FULL_NAME` varchar(60) COLLATE utf8_bin DEFAULT '' COMMENT '全名',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=710248 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `T_ORDER` (
  `ID` bigint(10) NOT NULL AUTO_INCREMENT COMMENT '主键,也是订单编号',
  `USER_NAME` varchar(10) DEFAULT NULL COMMENT '用户姓名',
  `MONEY` double(10,2) DEFAULT NULL COMMENT '订单金额',
  `CREATE_TIME` date DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `T_GOODS` (
  `ID` bigint(10) NOT NULL AUTO_INCREMENT COMMENT '主键,商品编号',
  `GOODS_NAME` varchar(10) DEFAULT NULL COMMENT '商品名称',
  `GOODS_PRICE` double(10,2) DEFAULT NULL COMMENT '商品单价',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `T_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(255) DEFAULT NULL,
  `USER_AGR` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `user_age_index` (`USER_AGR`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

